name: CI

on:
  push:
    branches:
      - main
      - 'test-ci/*'
      - 'refactor/*' # TODO
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install

      - name: Static check
        run: |
          pnpm eslint
          pnpm type-coverage
          pnpm type-check

      - name: Build
        run: pnpm build

      - name: Test
        run: |
          echo 'not for now'
          # pnpm unit-test

      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish
        if: github.ref_name == 'main'
        env:
          CI_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          CI_COMMIT_REF_NAME: ${{ github.ref_name }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_ENV: production
        run: |
          if [[ $(git log -n1 --format=%s) =~ "chore(release): bump" ]]; then
            pnpm publish
          fi
